# Generated by Django 5.2.1 on 2025-06-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quejas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(default='juanita', max_length=50),
            preserve_default=False,
        ),
    ]
